sonar.projectKey=cd-audio-tests
sonar.projectName=CD Audio - Application + Tests
sonar.sourceEncoding=UTF-8

sonar.sources=server,client/src
sonar.tests=server/tests,client/src/components/__tests__,client/src/services/__tests__,cypress/e2e
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,client/src/assets/**,client/public/**,server/tests/**,client/src/components/__tests__/**,client/src/services/__tests__/**,cypress/e2e/**

sonar.javascript.lcov.reportPaths=server/coverage/lcov.info,client/coverage/lcov.info
